# Generated by Django 5.1.5 on 2025-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0002_adminsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='voitures_photos/'),
        ),
    ]
