# Generated by Django 5.1.5 on 2025-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0003_voiture_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsite',
            name='nom',
        ),
        migrations.AddField(
            model_name='adminsite',
            name='motdepasse',
            field=models.CharField(default='pbkdf2_sha256$870000$yMuyWLIcJXYT88ws1TFrtS$Qb3avOHF/neeWaBDYuFLOWp7hSNnwBT36eb/wfNs4k8=', max_length=255),
        ),
    ]
