# Generated by Django 5.1.5 on 2025-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0004_remove_adminsite_nom_adminsite_motdepasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsite',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminsite',
            name='motdepasse',
            field=models.CharField(default='pbkdf2_sha256$870000$V9fcCkfYLNyPHhcfPFjM7k$hjweuzu/Mmhp9pEesAtCejlGmPU2/MY+gecR1cZt31M=', max_length=255),
        ),
    ]
