# Generated by Django 5.1.5 on 2025-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0005_adminsite_nom_alter_adminsite_motdepasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsite',
            name='nom',
        ),
        migrations.AlterField(
            model_name='adminsite',
            name='motdepasse',
            field=models.CharField(max_length=255),
        ),
    ]
